version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      nestjs:
        patterns: ['@nestjs/*']
      prisma:
        patterns: ['prisma', '@prisma/client']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    commit-message:
      prefix: 'ci'
